-- Create messages table linked to chat_sessions (or just loose for now if session ID tracking is complex on client)
-- For simplicity in this iteration, we will just store messages flat with a session_id provided by the client (or generated)

create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  session_id text not null, -- generated by AI SDK or Client
  role text not null, -- 'user', 'assistant', 'system'
  content text not null,
  tokens int
);

-- RLS
alter table public.messages enable row level security;

-- Drop existing policies to avoid "already exists" error
drop policy if exists "Allow public insert to messages" on public.messages;
drop policy if exists "Allow authenticated read messages" on public.messages;

-- Allow anon to insert messages (for the public chat)
create policy "Allow public insert to messages"
on public.messages
for insert
to anon
with check (true);

-- Allow authenticated (dashboard) to read
create policy "Allow authenticated read messages"
on public.messages
for select
to authenticated
using (true);
