"use server";

import { GoogleGenerativeAI } from "@google/generative-ai";
import { Resend } from "resend";
import * as cheerio from "cheerio";

// Initialize APIs
const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENERATIVE_AI_API_KEY || "");
// Remove top-level Resend init to unexpected behavior
// const resend = new Resend(process.env.RESEND_API_KEY);

// ... (keep interface AuditResult and analyzeWebsite function) ...

// ... (keep helpers scrapeWebsite, runPageSpeedAudit, runGeminiAnalysis) ...

// Helper: Send Email
async function sendAuditEmail(to: string, url: string, data: AIAnalysis, psi: any) {
  // Lazy init Resend
  const resend = new Resend(process.env.RESEND_API_KEY);

  const htmlContent = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #1e293b;">
      <h1 style="color: #4f46e5;">AI Audit Report: ${url}</h1>
      
      <div style="background: #f8fafc; padding: 20px; border-radius: 12px; margin: 20px 0;">
        <h2 style="margin-top: 0;">AI Readiness Score: <span style="color: #4f46e5; font-size: 1.5em;">${data.score}/100</span></h2>
        <p><strong>Odvetvie:</strong> ${data.industry}</p>
        <p>${data.summary}</p>
      </div>

      ${psi ? `
      <div style="background: #eef2ff; padding: 20px; border-radius: 12px; margin: 20px 0; border: 1px solid #c7d2fe;">
        <h3 style="margin-top: 0; color: #3730a3;">⚡ Rýchlosť webu (Mobile)</h3>
        <p style="font-size: 2em; font-weight: bold; margin: 10px 0; color: ${psi.performance >= 90 ? '#16a34a' : psi.performance >= 50 ? '#ca8a04' : '#dc2626'}">${psi.performance}/100</p>
        <ul style="padding-left: 20px; color: #4338ca;">
            <li>First Contentful Paint: <strong>${psi.fcp}</strong></li>
            <li>Largest Contentful Paint: <strong>${psi.lcp}</strong></li>
        </ul>
      </div>
      ` : ''}

      <h3>🚀 Príležitosti na automatizáciu</h3>
      ${data.opportunities.map(opp => `
        <div style="border-left: 4px solid #4f46e5; padding-left: 15px; margin-bottom: 20px;">
          <h4 style="margin: 0; color: #1e293b;">${opp.title}</h4>
          <p style="margin: 5px 0 0; color: #475569;">${opp.description}</p>
          <small style="color: #64748b;">Impact: ${opp.impact}</small>
        </div>
      `).join("")}

      <hr style="margin: 40px 0; border: none; border-top: 1px solid #e2e8f0;" />
      
      <p style="text-align: center; color: #64748b; font-size: 12px;">
        Generated by Marian Stancik AI Agent.<br/>
        <a href="mailto:marian@stancik.ai">Odpovedať na tento email</a>
      </p>
    </div>
  `;

  try {
    const { data: emailData, error } = await resend.emails.send({
      from: "Marian AI Agent <ai@marianstancik.dev>", // Forced Verified Domain
      to: to,
      subject: `🚀 Váš AI Audit Report pre ${url}`,
      html: htmlContent,
    });

    if (error) {
      console.error("Resend API Error:", error);
      throw new Error(`Resend failed: ${error.message}`);
    }
    console.log("Email sent successfully:", emailData);
  } catch (e) {
    console.error("Critical: Failed to send audit email.", e);
    // Don't crash the whole flow, just log it so we can see it in Vercel logs
  }
}
